spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneshop
    password: leanghourng123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
